[versions]
junit-jupiter = "5.10.0"
imgui-java = "1.87.6"

[libraries]
junit-jupiter = { module = "org.junit.jupiter:junit-jupiter", version.ref = "junit-jupiter" }
imgui-java = { module = "io.github.spair:imgui-java-app", version.ref = "imgui-java" }